#!/usr/bin/env bash
# Build "El Paso Monitor.app" — a thin macOS app over the existing conda env.
#
# The bundle just launches `python -m dashboard --app` from this repo with
# the elpaso-quake env's Python. Rebuild after moving the repo or recreating
# the env:
#
#   ./deploy/app/build_app.sh                # installs to /Applications
#   ./deploy/app/build_app.sh ~/Applications # or anywhere else

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
DEST="${1:-/Applications}"
APP="$DEST/El Paso Monitor.app"

PYTHON="$(conda run -n elpaso-quake python -c 'import sys; print(sys.executable)')"
# <conda_root>/envs/<env>/bin/python -> <conda_root>
CONDA_BASE="$(dirname "$(dirname "$(dirname "$(dirname "$PYTHON")")")")"
echo "Repo:   $REPO"
echo "Python: $PYTHON"
echo "Conda:  $CONDA_BASE"

# ── Remote-access credentials (kept OUT of git) ───────────────────────
# deploy/app/local.env is gitignored and holds DASHBOARD_USERNAME/PASSWORD.
# If present, the app binds 0.0.0.0 so browsers on the tailnet/LAN can
# connect (they get a login prompt; the local window never does). If
# absent, one is generated on first build so rebuilds keep the same
# password. Delete local.env and rebuild to rotate it.
LOCAL_ENV="$HERE/local.env"
if [ ! -f "$LOCAL_ENV" ]; then
    echo "Generating remote-access credentials -> $LOCAL_ENV"
    umask 177
    cat > "$LOCAL_ENV" <<CREDS
DASHBOARD_USERNAME=marc
DASHBOARD_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)
CREDS
    umask 022
fi
# shellcheck disable=SC1090
source "$LOCAL_ENV"
# Bind loopback only: remote access goes through `tailscale serve` (TLS,
# tailnet-only), so nothing listens on the LAN. See README Remote access.
HOST="127.0.0.1"

# ── Icon ──────────────────────────────────────────────────────────────
if [ ! -f "$HERE/AppIcon.icns" ]; then
    echo "Building icon..."
    "$PYTHON" "$HERE/make_icon.py"
    iconutil -c icns "$HERE/AppIcon.iconset" -o "$HERE/AppIcon.icns"
fi

# ── Bundle skeleton ───────────────────────────────────────────────────
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$HERE/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>El Paso Monitor</string>
    <key>CFBundleDisplayName</key>     <string>El Paso Monitor</string>
    <key>CFBundleIdentifier</key>      <string>org.elpaso.monitor</string>
    <key>CFBundleShortVersionString</key> <string>1.0</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>ElPasoMonitor</string>
    <key>CFBundleIconFile</key>        <string>AppIcon</string>
    <key>NSHighResolutionCapable</key> <true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/ElPasoMonitor" <<LAUNCHER
#!/bin/bash
# Generated by deploy/app/build_app.sh — paths/credentials are baked in;
# rebuild to update (credentials come from deploy/app/local.env, gitignored).
cd "$REPO"
mkdir -p logs
# Finder launches apps with a minimal PATH; give subprocesses the conda
# toolchain (detection resolves env pythons directly, but keep PATH sane
# for anything else that shells out).
export PATH="$(dirname "$PYTHON"):$CONDA_BASE/condabin:\$PATH"
export DASHBOARD_AUTH_ENABLED=1
export DASHBOARD_USERNAME='$DASHBOARD_USERNAME'
export DASHBOARD_PASSWORD='$DASHBOARD_PASSWORD'
exec "$PYTHON" -m dashboard --app --host $HOST >> logs/app.log 2>&1
LAUNCHER
chmod +x "$APP/Contents/MacOS/ElPasoMonitor"

echo "Built: $APP"
echo "Remote access: http://<this-mac's-tailscale-name-or-ip>:8000"
echo "  username: $DASHBOARD_USERNAME   password: (in $LOCAL_ENV)"
echo "Double-click it (or: open \"$APP\") to launch."
