#!/usr/bin/env bash
# Build "El Paso Monitor.app" — a thin macOS app over the existing conda env.
#
# The bundle just launches `python -m dashboard --app` from this repo with
# the elpaso-quake env's Python. Rebuild after moving the repo or recreating
# the env:
#
#   ./deploy/app/build_app.sh                # installs to /Applications
#   ./deploy/app/build_app.sh ~/Applications # or anywhere else

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
DEST="${1:-/Applications}"
APP="$DEST/El Paso Monitor.app"

PYTHON="$(conda run -n elpaso-quake python -c 'import sys; print(sys.executable)')"
echo "Repo:   $REPO"
echo "Python: $PYTHON"

# ── Icon ──────────────────────────────────────────────────────────────
if [ ! -f "$HERE/AppIcon.icns" ]; then
    echo "Building icon..."
    "$PYTHON" "$HERE/make_icon.py"
    iconutil -c icns "$HERE/AppIcon.iconset" -o "$HERE/AppIcon.icns"
fi

# ── Bundle skeleton ───────────────────────────────────────────────────
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$HERE/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>El Paso Monitor</string>
    <key>CFBundleDisplayName</key>     <string>El Paso Monitor</string>
    <key>CFBundleIdentifier</key>      <string>org.elpaso.monitor</string>
    <key>CFBundleShortVersionString</key> <string>1.0</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>ElPasoMonitor</string>
    <key>CFBundleIconFile</key>        <string>AppIcon</string>
    <key>NSHighResolutionCapable</key> <true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/ElPasoMonitor" <<LAUNCHER
#!/bin/bash
# Generated by deploy/app/build_app.sh — paths are baked in; rebuild to update.
cd "$REPO"
mkdir -p logs
exec "$PYTHON" -m dashboard --app >> logs/app.log 2>&1
LAUNCHER
chmod +x "$APP/Contents/MacOS/ElPasoMonitor"

echo "Built: $APP"
echo "Double-click it (or: open \"$APP\") to launch."
